import ToastProvider from "@/providers/ToastProvider";
import "./globals.css";
import { Poppins } from "next/font/google";
import AuthContext from "@/context/authContext";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import InitialDataFetcherProvider from "@/providers/InitialDataFetchProvider";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={`${poppins.variable} font-poppins  bg-gray-100`}>
          <ReactQueryProvider>
            <ReduxProvider>
              <AuthContext>
                <ToastProvider />
                <InitialDataFetcherProvider>
                  {children}
                </InitialDataFetcherProvider>
              </AuthContext>
            </ReduxProvider>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
